<?php

/**
 * @file
 * TODO: insert description here.
 */

define('FRONT_MIGRATION_DB', 'frontd6');
define('FRONT_MIGRATION_FILES', 'http://localhost/front/sites/default/legacy_files');
define('FRONT_TERM_SECTION', 19);
define('FRONT_TERM_SECTION_NAME', 'section');
define('FRONT_TERM_TOPIC', 20);
define('FRONT_TERM_TOPIC_NAME', 'topic');

function migrate_front_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Retrieve the set of term associated with a node from the migration database.
 */
function migrate_front_migration_get_terms($vid, $tvid) {
  $query = db_select(FRONT_MIGRATION_DB . '.term_node', 'tn');
  $query->join(FRONT_MIGRATION_DB . '.term_data', 'td', 'tn.tid = td.tid');
  $query->addField('td', 'name');
  $query->condition('tn.vid', $vid, '=');
  $query->condition('td.vid', $tvid, '=');
  $query->orderBy('tn.tid', 'ASC');
  $result = $query->execute()->fetchCol();

  return is_array($result) && !empty($result) ? implode(',', $result) : NULL;
}
